# Site settings
title: Hannah Tran
email: foo@example.com
description: > # this means to ignore newlines until "baseurl:"
  Explain technical concepts to any audience. Hannah has experience talking
  about Blockchain, Docker, Confluence, Microsoft Azure, and more to diverse
  groups of people, bringing to life the complex in understandable terms.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hannahjtran.com" # the base hostname & protocol for your site
twitter_username: jollyhannah
github_username:  jgg01

# Build settings
markdown: kramdown
